version: '3.9'

services:
    mongo:
        image: mongo:7
        container_name: mongo
        restart: unless-stopped
        ports:
            - '${PORT_MONGO}:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DB}
        volumes:
            - mongo-data:/data/db

    back:
        image: node:20-alpine
        container_name: back
        working_dir: /app
        depends_on: [mongo]
        ports:
            - '${PORT_BACK}:3000'
        environment:
            CLERK_SECRET_KEY: '${CLERK_SECRET_KEY}'
            NODE_ENV: development
            PORT: '3000'
            NEXT_TELEMETRY_DISABLED: '1'
            MONGODB_URI: 'mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_DB}?authSource=admin'
            CHOKIDAR_USEPOLLING: 'true'
            WATCHPACK_POLLING: 'true'
            URL_FRONT: '${URL_FRONT}'
        volumes:
            - ./back:/app
            - back-node-modules:/app/node_modules
            - back-next:/app/.next
        command: >
            sh -c "
              apk add --no-cache libc6-compat &&
              (npm ci || npm install) &&
              npm run dev -- -p 3000 -H 0.0.0.0
            "

    front:
        image: node:20-alpine
        container_name: front
        working_dir: /app
        depends_on: [back]
        ports:
            - '${PORT_FRONT}:3000'
            - '${PORT_SOCKET}:3001'
        environment:
            CHOKIDAR_USEPOLLING: 'true'
            CLERK_SECRET_KEY: '${CLERK_SECRET_KEY}'
            NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: '${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}'
            NEXT_PUBLIC_URL_BACK: '${NEXT_PUBLIC_URL_BACK}'
            NEXT_PUBLIC_URL_FRONT: '${NEXT_PUBLIC_URL_FRONT}'
            NEXT_PUBLIC_URL_SOCKET: '${NEXT_PUBLIC_URL_SOCKET}'
            NEXT_TELEMETRY_DISABLED: '1'
            NODE_ENV: development
            PORT: '3000'
            URL_BACK: '${URL_BACK}'
            URL_FRONT: '${URL_FRONT}'
            URL_SOCKET: '${URL_SOCKET}'
            WATCHPACK_POLLING: 'true'
        volumes:
            - ./front:/app
            - front-node-modules:/app/node_modules
            - front-next:/app/.next
        command: >
            sh -c "
              apk add --no-cache libc6-compat &&
              (npm ci || npm install) &&
              npm run dev -- -p 3000 -H 0.0.0.0
            "

    mongo-express:
        image: mongo-express:1
        depends_on: [mongo]
        ports:
            - '${PORT_MONGO_EXPRESS}:8081'
        environment:
            ME_CONFIG_MONGODB_URL: 'mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/?authSource=admin'
            ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}

volumes:
    mongo-data:
    front-node-modules:
    back-node-modules:
    front-next:
    back-next:
