import type { Metadata } from 'next'
import {
    ClerkProvider,
    SignInButton,
    SignUpButton,
    SignedIn,
    SignedOut,
    UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Drawer } from '@/components/drawer'

import { Toaster } from 'react-hot-toast'
import { ClearStoreOnLogout } from '@/components/auth'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: '4PROJ FRONT',
    description: 'Generated by create next app',
}

const RootLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode
}>) => {
    return (
        <html suppressHydrationWarning lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                suppressHydrationWarning
            >
                <ClerkProvider>
                    <Toaster />

                    <ClearStoreOnLogout />

                    <div className="navbar bg-base-100 shadow-sm">
                        <header className="flex justify-end items-center p-4 gap-4 h-16">
                            <SignedOut>
                                <div className="flex w-[95vw] justify-between">
                                    <button>
                                        <a href="/">SUPRSS</a>
                                    </button>

                                    <div>
                                        <SignInButton />

                                        <SignUpButton>
                                            <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                                                Sign Up
                                            </button>
                                        </SignUpButton>
                                    </div>
                                </div>
                            </SignedOut>

                            <SignedIn>
                                <div className="flex w-[95vw] justify-between">
                                    <Drawer />
                                    <UserButton />
                                </div>
                            </SignedIn>
                        </header>
                    </div>

                    {children}
                </ClerkProvider>
            </body>
        </html>
    )
}

export default RootLayout
